Variables {GJE}
Terminals {cab}
Equation: caaacJbababcbabaaccaabbabaaacabcababcaaaabaaccEcccabbbabccacabccaacbbabcbbcbacbccbccbaaacba = caaacJbababcbabaaccaabbabaaaGcbbcbacbccbccbaaacba
SatGlucose(100)