Variables {ME}
Terminals {gfabcde}
Equation: bggfadfebcbcddebgbadgabffeegcbbgceaceaefefeababacedfcafdbEbgc = bggfadfebcbcddebgbadgabffeegcbbgcMafbeegcfafgbfbceadaeecaegfadgebbfdcddafcaeadaafdeabgeccceagaecdbgc
SatGlucose(100)