Variables {BGK}
Terminals {gfacbde}
Equation: defcfacdggfKcfbeddecfcgegddagccbbbeebcdegadcddbcbcfbadeeadafcBbbfgebdbeeabdaaabffageddg = defcfacdggfcddcfGaccfafcdgdefffacfecdfedbagacfgefgeabbfgebdbeeabdaaabffageddg
SatGlucose(100)