Variables {A}
Terminals {gfacbde}
Equation: gcfedcedggeedcfedgfcgbabgcgAgacaedgdeaeddafdcdefgbafdabfeaddbgfeddefadaeddcdaegbbbccdbffdfbefbdgcdbfggfcdffgfcabebdgabdg = gcfedcedggeedcfedgfcgbabgcgdccffccddcffgacaedgdeaeddafdcdefgbafdabfeaddbgfeddefadaeddcdaegbbbccdbffdfbefbdgcdbfggfcdffgfcabebdgabdg
SatGlucose(100)