Variables {FE}
Terminals {gacbjfhdei}
Equation: aijebibadgbbbgebhfjaieeagjfeeceibFghjEeddhiffcgbdibgheacdijbgighgaiibhgachdjj = aijebibadgbbbgebhfjaieeagjfeeceibcffjjfdbciciaefighjEeddhiffcgbdibgheacdijbgighgaiibhgachdjj
SatGlucose(100)