Variables {DJ}
Terminals {bac}
Equation: bbaabbbacbJccbccccbabaacbabaabbaacbbacaaaaabcbabccccbccaabacbbccbcbaaD = bbaabbbacbbbbbcbcbcacbbabDaabaaabacDbbcbbcacccbbDaccabbaabccccDaccbccccbabaacbabaabbaacbbacaaaaabcbabccccbcDabacbbccbcbaaca
SatGlucose(100)