Variables {HGJ}
Terminals {gacbjfhdei}
Equation: debgjbaigeeijejgaJgiicHjegjjbeiidhebbgifjcgigejeddaiahageajjfiejajdajfbcjehgeec = debgjbaigeeijejgabfcgecjfaGfjcgigejeddaiahageajjfiejajdajfbcjehgeec
SatGlucose(100)