Variables {A}
Terminals {gfacbde}
Equation: feefdAgfeaceebadcefdbddfgdbgcAAddfcecbaabacgdadeceaeabfbbAfebeffadbffdgcfgbgdaedgccedcbdgaccbdfdefabadf = feefdeggfeaceebadcefdbddfgdbgcegAddfcecbaabacgdadeceaeabfbbegfebeffadbffdgcfgbgdaedgccedcbdgaccbdfdefabadf
SatGlucose(100)