Variables {BJEI}
Terminals {gfabcde}
Equation: dcbgbggeagdfbbgdfebffacgEgcedacebdfabcbfafgacggebbfegfdceeabecgdgbcd = dcbgbggeagdfJbBfbffgbegacfdbdIbdfabcbfafgacggebbfegfdceeabecgdgbcd
SatGlucose(100)