Variables {A}
Terminals {abcde}
Equation: cdacdeceecacedddeaedaebdcababaedbbddeeceaecccbdeecbdcecbaedbacacdebecedcabccdabccabbddbcbbacebcbbabcbdabaadebecabaccbaaceaecaabebcada = cdacdeceecacedddeaedaebdcababaedbbddeeceaecccbdeecbdAcdabccabbddbcbbacebcbbabcbdabaadebecabaccbaaceaecaabebcada
SatGlucose(100)