Variables {BGCD}
Terminals {gacbfhdei}
Equation: eccGgiafdaeCbdaebcdheefccbbadiihhiBgheghihfceciagbggeecedbhdfggeadccfdichdcecdfg = eccGgiaDhfgheghihfceciagbggeecedbhdfggeadccfdichdcecdfg
SatGlucose(100)