Variables {CA}
Terminals {gabcfhdei}
Equation: dgabddihghgafhhdhiigiffddgbgcbihhfaiccbicchihaddbfficdbdhdbibifceaceifbifadcfeacdfhefhacehiicbgiedhhcbhbicfdbiehfgaadhcahecicbchcdbabfiidfbdf = dgabddihghgafhhdhiigiffdChhfaicAacehiicbgiedhhcbhbicfdbiehfgaadhcahecicbchcdbabfiidfbdf
SatGlucose(100)