Variables {HLC}
Terminals {gfabcde}
Equation: fgdgbgeaafLfabfafbefgbdcaffcaagbccbHagdbfabbcceccgcecefeadeagddgeebdedbcfgabgeagfggdebecccecfcgf = fgdgbgeaafbfeeedefeCabbcceccgcecefeadeagddgeebdedbcfgabgeagfggdebecccecfcgf
SatGlucose(100)