Variables {BAF}
Terminals {gfabcde}
Equation: deecbcgcfgbebdccagageBegbAfdddbaabfegbbggcadfaaeagdf = deecbcgcfgbebdccagageBegbebcaeccedbedefbfdFgbagebcbfacgadbefcffcgceeeddfdddbaabfegbbggcadfaaeagdf
SatGlucose(100)