Variables {BD}
Terminals {gabcfhde}
Equation: bebedhdDfcadechdaddffaebfhdeBchdegeecbbacggbgcbefcfhbgabhcgecfgeehaeafaaaahchbegehchegbcegbcdhbcd = bebedhdDfcadechdaddffaebfhdegccchcbdcehedcehaeachghehhededaddhcehgbchdegeecbbacggbgcbefcfhbgabhcgecfgeehaeafaaaahchbegehchegbcegbcdhbcd
SatGlucose(100)