Variables {HJE}
Terminals {gfacbde}
Equation: ccdegdegecdfbbfdgeedcaHafacbdfaeegdbaJeaacaEgefffccecfddcddcbgffcdaagebfeafddedegcdfe = ccdegdegecdfbbfdgeedcafacafacbdfaeegdbaJeaacaEgefffccecfddcddcbgffcdaagebfeafddedegcdfe
SatGlucose(100)