Variables {BCD}
Terminals {gacbfjhdei}
Equation: eafBjgfaihdfcbgffCgebgjgfdebeajefbe = eafbgieagfdcahedjjjdcjgfaihdfcbgffbafedhbebghehgfehibbjdejbdafiidcbbecDiahceaggigheiebjecfgebgjgfdebeajefbe
SatGlucose(100)