Variables {AC}
Terminals {gfacbde}
Equation: fdfafeafegAcbgcdbgbfbgfeacegbcddgagbebgeadbbacdfaefaeffffbfgagaggebbcccddacecaddfed = fdfafeafegbbfbgegffgedegdfcgebgecgccadgdaefbfCdbbacdfaefaeffffbfgagaggebbcccddacecaddfed
SatGlucose(100)