Variables {CE}
Terminals {fabcde}
Equation: ccbccafdefdbfbcecefefbbbfefCdebEcbdfcbedcafaebbcdebdafdcbbedbbaeaadcaccbebcfffdccbfbabfcafe = ccbccafdefdbfbcecefefbbbfefCdebcbfbdefcbdfcbedcafaebbcdebdafdcbbedbbaeaadcaccbebcfffdccbfbabfcafe
SatGlucose(100)