Variables {AC}
Terminals {gabcfhde}
Equation: cebhhefgdhhfdbdhcghaadfhagcgceeffahfeeaecgeaafgebecchabcaaecefgAdecbaadbaghchcfcgdbhchfbcfehbefgehgfadhdfhebfebdfhce = cebhhefgdhhfdbdhcghaadfhagcgceeffahfeeaecgeaafgebecchabcaCbfebdfhce
SatGlucose(100)