Variables {DE}
Terminals {gfacbde}
Equation: dffddgcefafggbeafadafbcacfdfcdffbfcbeeaegbaegcdEfeecegffcfeaagfcadfcffdeddbgdbbgceeb = dffddgcefafggbeafadafbcacfdfcdffbfcbeeaegbaegcdbddcaddgfgadacdgfgbdbccDffcecbaefcfegebadbfagecfbdbfafeecegffcfeaagfcadfcffdeddbgdbbgceeb
SatGlucose(100)