Variables {A}
Terminals {acbde}
Equation: baeeaaaeebbbdcddcbdcbcbAbbddaacebccdaaedeccbdbeeedaacddedacdbcedbbabcdbbccb = baeeaaaeebbbdcddcbdcbcbcdccbebdabceecacceaeabbddaacebccdaaedeccbdbeeedaacddedacdbcedbbabcdbbccb
SatGlucose(100)