Variables {BC}
Terminals {gfabcde}
Equation: fabeafbgdaggecacdcadgfbgegfdfeebcggecaaebcefabgaaecdbddcfdBfccabggdaedcafgcbadaagdaaebc = fabeafbgdaggecacdcadgfbgegfdfeebcggecaaebcefabCecfdecdcfaagfaeeaccbafccabggdaedcafgcbadaagdaaebc
SatGlucose(100)