Variables {BAMJ}
Terminals {gacbfhdei}
Equation: cfaeggdifAiigbacihegbhifichcbJahBcfbcfideggigdfigciibeefhigcegaeiaefihgdffbaicfiehfhai = cfaeggdifefhahcciigbacihegbhifichMfdhicfbcfideggigdfigciibeefhigcegaeiaefihgdffbaicfiehfhai
SatGlucose(100)