Variables {A}
Terminals {gabcfhdei}
Equation: fbaiigcfaggfiehhgbacfbccafcbaebecbhfbdidaedhbgfcddfcbAfhgbfcfcccgfdafeehaibhficaedfficcdgae = fbaiigcfaggfiehhgbacfbccafcbaebecbhfbdidaedhbgfcddfcbcffbcdabhgahehfdecfaffdedafgicdacdcgebecagchdccgfacadbahgiagfhgbfcfcccgfdafeehaibhficaedfficcdgae
SatGlucose(100)