Variables {HLKE}
Terminals {gacbfhdei}
Equation: ebcgadKdiecfaiifeeafffgafbhgdccdhfffdeffiebhieiefhHhhbehehbbgeghiggcdfbgadbgcdfcfdhhcfhfdcfcifefhggifheggbebfcca = ebcgLecfaiifeeafffgafbhEeggbebfcca
SatGlucose(100)