Variables {AC}
Terminals {facbde}
Equation: aaadbcbAccdcccdebbcffcbbadAfafcbccbAedfaAccaacffaaAfeafacdccadabbdbAeccbcbcdedecaaddaebfddbaabcabffadcaeAaababfaeed = aaadbcbfccdcccdebbcAAcbbadAfaAcbccCdabbdbAeccbcbcdedecaaddaebAddbaabcabAAadcaefaababfaeed
SatGlucose(100)