Variables {AD}
Terminals {cab}
Equation: acabAbccbccabacbcccbabbbbaaccaccbacbcacabcbaaabcabacacaaccbcccacaaabaaa = acabccbacbbbbbcbbcccbbaacabbDccaccbacbcacabcbaaabcabacacaaccbcccacaaabaaa
SatGlucose(100)