Variables {GAED}
Terminals {facbde}
Equation: aadbabccceabfffdcbdaadffeGfdeccdddefededcdbeecfabcAfbcbEefcceeaadbadcfacddbffddcadeed = aadbabccceabfffdcbdaadffeGfdeccdddefededcdDdbffddcadeed
SatGlucose(100)