Variables {A}
Terminals {gabcfhdei}
Equation: ghaiehabecigefgibdchcidcbhchagdgchiacdchcghfcaafbfgaghcgedddaaghchgdhgghibegagghaiciacdgbcadhbcgfifefgcbfcagddebddbeibedfecbh = ghaiehabecigefgibdchcidcbhchagdgAbddbeibedfecbh
SatGlucose(100)