Variables {AED}
Terminals {gfabcde}
Equation: ffAbAeagacdebfegegdbeaeggdaegeegebfcgbfgefeAedafbAdddfEbbbaaAdaaccabAdfedffeea = ffcbceagaAdebfegegdbeaeggdaegeegebfcgDAdddfEbbbaacdaaAcabAdfedffeea
SatGlucose(100)