Variables {B}
Terminals {gacbjfhdei}
Equation: hbgdjgabehbcihfhggfdijbjcBgiedhcjcibfffacgbgejibbgjadjeddhjehjj = hbgdjgabehbcihfhggfdijbjchjjfbfeijebfjabciadjchegiiedjdiihifdbfebiechbegiedhcjcibfffacgbgejibbgjadjeddhjehjj
SatGlucose(100)